// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4jWTYLjMvWY8nrbq5gdDSU
// Component: 7fe5zO4wma
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: 4jWTYLjMvWY8nrbq5gdDSU/projectcss
import sty from "./PlasmicPrimaryButton.module.css"; // plasmic-import: 7fe5zO4wma/css

export type PlasmicPrimaryButton__VariantMembers = {
  isSelected: "isSelected";
};

export type PlasmicPrimaryButton__VariantsArgs = {
  isSelected?: SingleBooleanChoiceArg<"isSelected">;
};

type VariantPropType = keyof PlasmicPrimaryButton__VariantsArgs;
export const PlasmicPrimaryButton__VariantProps = new Array<VariantPropType>(
  "isSelected"
);

export type PlasmicPrimaryButton__ArgsType = {
  destination?: string;
  title?: React.ReactNode;
};

type ArgPropType = keyof PlasmicPrimaryButton__ArgsType;
export const PlasmicPrimaryButton__ArgProps = new Array<ArgPropType>(
  "destination",
  "title"
);

export type PlasmicPrimaryButton__OverridesType = {
  root?: p.Flex<"a"> & Partial<LinkProps>;
  unstyledButton2?: p.Flex<"div">;
};

export interface DefaultPrimaryButtonProps {
  destination?: string;
  title?: React.ReactNode;
  isSelected?: SingleBooleanChoiceArg<"isSelected">;
  className?: string;
}

function PlasmicPrimaryButton__RenderFunc(props: {
  variants: PlasmicPrimaryButton__VariantsArgs;
  args: PlasmicPrimaryButton__ArgsType;
  overrides: PlasmicPrimaryButton__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  return (
    <p.PlasmicLink
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.a,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        {
          [sty.rootisSelected]: hasVariant(variants, "isSelected", "isSelected")
        }
      )}
      component={Link}
      href={args.destination}
      platform={"nextjs"}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"unstyledButton2"}
        data-plasmic-override={overrides.unstyledButton2}
        hasGap={true}
        className={classNames(projectcss.all, sty.unstyledButton2)}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___92MQ
              )}
            >
              {"Product"}
            </div>
          ),

          value: args.title,
          className: classNames(sty.slotTargetTitle)
        })}
      </p.Stack>
    </p.PlasmicLink>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "unstyledButton2"],
  unstyledButton2: ["unstyledButton2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "a";
  unstyledButton2: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPrimaryButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPrimaryButton__VariantsArgs;
    args?: PlasmicPrimaryButton__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPrimaryButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPrimaryButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicPrimaryButton__ArgProps,
          internalVariantPropNames: PlasmicPrimaryButton__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicPrimaryButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPrimaryButton";
  } else {
    func.displayName = `PlasmicPrimaryButton.${nodeName}`;
  }
  return func;
}

export const PlasmicPrimaryButton = Object.assign(
  // Top-level PlasmicPrimaryButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    unstyledButton2: makeNodeComponent("unstyledButton2"),

    // Metadata about props expected for PlasmicPrimaryButton
    internalVariantProps: PlasmicPrimaryButton__VariantProps,
    internalArgProps: PlasmicPrimaryButton__ArgProps
  }
);

export default PlasmicPrimaryButton;
/* prettier-ignore-end */
